# Generated by Django 5.1.1 on 2024-09-26 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='numero_seguimiento',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
